baseurl = "https://www.tfgordon.de"  # "https://tfgordon.github.io/"
title = "Thomas F. Gordon"
author = "Thomas F. Gordon"
copyright = "copyright &copy; 2015-2021 Thomas F. Gordon. Creative Commons Attribution-ShareAlike 4.0 International License "
languageCode = "en-us"  
# contentdir = "content"
theme = "blackburn" #  "ananke"  
# layoutdir = "layouts"
publishdir =  "../pub"
builddrafts = true
canonifyurls = true
paginate = 10

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"

[permalinks] 
  post = ":year/:month/:day/:title/"
  fixed = ":title/"

[params]
  subtitle = "Argumentation Technology"
  highlightjs = "androidstudio"
  dateFormat = "2 Jan 2006, 15:04"

[Github]
  url = "https://github.com/tfgordon/tfgordon.github.io"
  head = "master"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-file fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
#  [[menu.main]]
#    name = "About"
#    pre = "<i class='fa fa-file fa-fw'></i>"
#    weight = 2
#    identifier = "about"
#    url = "/about/"
  [[menu.main]]
    name = "Resume"
    pre = "<i class='fa fa-file fa-fw'></i>"
    weight = 3
    identifier = "resume"
    url = "/resume/"
  [[menu.main]]
    name = "Publications"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 5
    identifier = "publications"
    url = "/publications/"
  [[menu.main]]
    name = "Software"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 5
    identifier = "software"
    url = "/software/"
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 6
    identifier = "projects"
    url = "/projects/"
  [[menu.main]]
    name = "Service"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 7
    identifier = "service"
    url = "/professional-service/"
  [[menu.main]]
    name = "Related"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 8
    identifier = "related"
    url = "/related/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 9
    url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

 
  # Techie
  github = "carneades/carneades-4"
